apiVersion: apps/v1

kind: Deployment

metadata:
  name: web-app

spec:
  
  #minReadySeconds: 30
  replicas: 1
  
  selector:
    matchLabels:
      app: web-app 
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
---

apiVersion: apps/v1
    
kind: Deployment

metadata:
  name: position-tracker

spec:
  #minReadySeconds: 30      
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
        - name: position-tracker
          image: richardchesterwood/k8s-fleetman-position-tracker:release1
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice




# apiVersion: apps/v1
    
# kind: Deployment

# metadata:
#   name: queue

# spec:
#   #minReadySeconds: 30      
#   replicas: 1
#   selector:
#     matchLabels:
#       app: queue
#   template:
#     metadata:
#       labels:
#         app: queue
#     spec:
#       containers:
#         - name: queue
#           image: richardchesterwood/k8s-fleetman-queue:release1
# ---

# apiVersion: apps/v1
    
# kind: Deployment

# metadata:
#   name: position-simulator

# spec:
#   #minReadySeconds: 30      
#   replicas: 1
#   selector:
#     matchLabels:
#       app: position-simulator
#   template:
#     metadata:
#       labels:
#         app: position-simulator
#     spec:
#       containers:
#         - name: position-simulator
#           image: richardchesterwood/k8s-fleetman-position-simulator:release1
#           env:
#           - name: SPRING_PROFILES_ACTIVE
#             value: production-microservice


# ---

